# Generated by Django 4.2.2 on 2023-07-01 16:10

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examenfisico",
            name="hallazgo_anormal",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="historia_enfermedad_actual",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="historiasocioambiental",
            name="otas_vacunas",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="historiasocioambiental",
            name="que_animales",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="hojadeegreso",
            name="diagnostico_definitivo_egreso",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="hojadeegreso",
            name="motivo_de_inreso",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="hojadeegreso",
            name="observaciones",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="hojadeegreso",
            name="otros_diagnosticos",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="hojadeegreso",
            name="resumen_examen_fisico",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="hojadeegreso",
            name="resumen_sindromico",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="hojadeegreso",
            name="tratamiento",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="interrogatorio",
            name="detallar_hallazgo_anormal",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="interrogatorio",
            name="digestivo_formula_dentaria",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="interrogatorio",
            name="digestivo_higado_borde_superior_en",
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name="interrogatorio",
            name="toxicos_otros",
            field=django_quill.fields.QuillField(),
        ),
    ]
